2021-06-27 22:50:29,257	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:29,258	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/jsonws/invoke
2021-06-27 22:50:30,875	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:30,875	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-06-27 22:50:30,960	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:30,960	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-06-27 22:50:32,135	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:32,135	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-27 22:50:33,013	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:33,013	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-27 22:50:33,159	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:33,160	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /solr/admin/info/system
2021-06-27 22:50:34,987	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:34,987	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /wp-content/plugins/wp-file-manager/readme.txt
2021-06-27 22:50:36,527	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:36,527	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /console/
2021-06-27 22:50:37,554	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:37,555	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /Autodiscover/Autodiscover.xml
2021-06-27 22:50:37,672	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:37,672	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /index.php
2021-06-27 22:50:39,668	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-27 22:50:39,668	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /_ignition/execute-solution
2021-06-28 01:01:44,037	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 01:01:44,037	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-06-28 01:01:45,251	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 01:01:45,252	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 01:18:18,467	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 01:18:18,468	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 02:16:29,976	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 02:16:29,976	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 02:30:48,118	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 02:30:48,119	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-06-28 02:30:50,445	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 02:30:50,446	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 02:53:06,886	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 02:53:06,886	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /owa/
2021-06-28 02:53:21,374	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 02:53:21,375	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 04:44:24,579	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'api.binance.com'. You may need to add 'api.binance.com' to ALLOWED_HOSTS.
2021-06-28 04:44:24,579	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/v1/time
2021-06-28 05:45:56,072	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:45:56,072	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 05:45:56,157	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:45:56,157	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /_ignition/execute-solution
2021-06-28 05:45:57,033	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:45:57,033	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /index.php
2021-06-28 05:45:59,769	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:45:59,770	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 05:45:59,771	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:45:59,771	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/jsonws/invoke
2021-06-28 05:46:01,826	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:46:01,826	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /Autodiscover/Autodiscover.xml
2021-06-28 05:46:04,342	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:46:04,342	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-06-28 05:46:04,470	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:46:04,470	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /console/
2021-06-28 05:46:07,742	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:46:07,742	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-06-28 05:46:07,794	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:46:07,795	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /mifs/.;/services/LogService
2021-06-28 05:46:10,590	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:46:10,591	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /wp-content/plugins/wp-file-manager/readme.txt
2021-06-28 05:53:37,235	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 05:53:37,236	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /actuator/health
2021-06-28 06:08:51,257	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 06:08:51,257	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 06:10:23,571	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 06:10:23,571	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 06:19:58,256	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 06:19:58,256	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-06-28 06:19:58,863	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 06:19:58,864	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 06:46:55,041	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'api.binance.com'. You may need to add 'api.binance.com' to ALLOWED_HOSTS.
2021-06-28 06:46:55,042	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/v1/time
2021-06-28 07:24:37,998	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 07:24:37,998	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 07:41:20,527	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 07:41:20,527	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
2021-06-28 08:00:04,304	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 08:00:04,305	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 09:35:22,695	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 09:35:22,695	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:07:12,195	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:07:12,196	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:10:41,455	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:10:41,456	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:10:41,962	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:10:41,963	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:11:46,714	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:11:46,715	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:14:24,655	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:14:24,655	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:17:14,809	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:17:14,809	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:22:19,115	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:22:19,116	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /owa/
2021-06-28 10:25:01,088	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /favicon.ico
2021-06-28 10:46:42,059	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': [''], 'university_area': ['2'], 'university': ['1'], 'faculty': ['196'], 'department': ['1'], 'professor_name': [''], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['9EcfIkgr7EjGnjWbcAI344vJkYTJfSCdlbKGsDwlwMv2z08ydowxNs3L4logqE6i']}>
2021-06-28 10:50:10,506	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:50:10,507	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 10:54:36,730	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 10:54:36,731	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 12:47:41,722	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /apple-touch-icon-120x120-precomposed.png
2021-06-28 12:47:41,733	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /apple-touch-icon-120x120.png
2021-06-28 12:47:41,746	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /apple-touch-icon-precomposed.png
2021-06-28 12:47:41,788	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /apple-touch-icon.png
2021-06-28 12:47:44,888	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': [''], 'university_area': [''], 'university': [''], 'faculty': [''], 'department': [''], 'professor_name': [''], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['EvDQ65QXONJD9xBYzhVFtWP5ZaPJ5uvh2OtAgBBNnoFTJxbQ6kyBXmGXuz5XxJYK']}>
2021-06-28 12:56:57,180	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 12:56:57,180	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /_ignition/execute-solution
2021-06-28 14:27:56,443	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 14:27:56,444	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 14:35:49,370	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 14:35:49,370	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 14:44:01,613	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 14:44:01,613	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-06-28 14:44:02,127	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 14:44:02,128	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 15:04:51,501	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:04:51,501	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 15:07:13,335	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:13,335	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/jsonws/invoke
2021-06-28 15:07:14,049	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:14,050	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /solr/admin/info/system
2021-06-28 15:07:14,937	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:14,938	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-06-28 15:07:15,527	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:15,528	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /index.php
2021-06-28 15:07:16,723	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:16,723	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 15:07:17,299	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:17,300	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 15:07:17,586	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:17,587	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /wp-content/plugins/wp-file-manager/readme.txt
2021-06-28 15:07:18,457	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:18,457	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /Autodiscover/Autodiscover.xml
2021-06-28 15:07:18,472	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:18,472	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-06-28 15:07:19,342	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:19,342	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /console/
2021-06-28 15:07:20,584	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 15:07:20,584	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /_ignition/execute-solution
2021-06-28 16:50:20,895	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 16:50:20,895	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 17:06:40,061	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 17:06:40,061	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 18:04:52,342	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 18:04:52,343	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 18:27:38,671	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 18:27:38,671	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /owa/auth/logon.aspx
2021-06-28 20:34:03,845	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 20:34:03,845	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-28 21:26:59,552	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': ['宇宙'], 'university_area': [''], 'university': [''], 'faculty': [''], 'department': [''], 'professor_name': [''], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['Lbt4tM30GvIFdBnmZSLdTczV7TYEQPTX0PyBTUOOJrSWIvu4Ngo6Gho3IC3f7kjK']}>
2021-06-28 21:27:02,187	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': ['宇宙'], 'university_area': [''], 'university': [''], 'faculty': [''], 'department': [''], 'professor_name': [''], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['iFCjnAYHYYOiOWZXkFww6HNa5vU2doPdxjHQNIJv1UYzjQ6F839pTMCiGeZDuTf0']}>
2021-06-28 21:42:43,021	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com'. You may need to add 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com' to ALLOWED_HOSTS.
2021-06-28 21:42:43,021	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /admin/view/javascript/common.js
2021-06-28 22:09:14,650	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-28 22:09:14,651	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /owa/
